sudo: required 
language: cpp
services:
  - docker
env:
  global:
    - secure:  "JvSTeBXyaRP34+kyrFcmDcV8vZDzMxfNJrwA7NQE5yf2fD9Se6D/Vkhg5BWaY1KP1KfQDGddm9tKugges/COCKAOzjGsW2Fk+upVYvYwkNdG0ICMUxo4HtjFr+OfOvj9tk0NQB9hKclKUv9Xpa128jlF9HTsRZ87EkcRojiwZMhZsm5YlCueh4l9Ngn47xiPbQL/VnnknkStEjI3kOb86cBiqlG/Wkw1eaA3GYKxd5J4KqfCQGpK7qD5sLofP6LYGDDJsIEBYZyBFpPPqOPckeQv4hq9oDDZzBDGyFmTviVlmukWpteVrlikyz2gjx7DgIDHTXevULbVOP8q6ZseP83THY0oJP4dfhmMpwIJufh1/H8+kABul5Xh5Z+ds05WUfE9VjcIyxd7lMiS+u4kjvvZhO7srJ65mV9JncZBZ97xIs8Yi2ZEhgVnwo8aZI7uQIQyukvQBIrUkiggiIJc9YeNAbreF5UjwlKbDlClA0+XQ1DsZ3zRuG3GaRj/3ouxBIrmQcUbJ6bNiuhRrpiAkxu72kCPaxnUKwiIIuuss+lL6SZB4SdX1cGgpZLyqAKJUM1xoOUze9CI97v5S/Ym3VH1CX8qOyQ9nShk1/WKlrL52Z7O/MzhGqroxDPW/5eyw/di0PxbrBFH641glsHOsNT+c3BoiZb9dmWNFFjvDbw=" # DOCKER_USER
    - secure: "BTPdUDeyZjgftMSsCRkAHr/3IsKdld/5vgEV1s02uAlw8H96uYQItYvPAxfdm0Llzlpb+O3rafplzthNnivJI3r4VyWuT2QeqSPAhPYJ7JSgGLYUrXa5amZQM7x2eOHHULkddFjYC8TTOWx4VDPoL2rbqLFDPaTqBod37pd3DxFFRtTAr9NE8FuNe81SuL/Dihz1azcEy1WvmizmxNuVc7dmH8ZiBaQPg+T22bStL3MQJGxS0vGO0wUB/Df8CO4XuYUzV/D+NrRDD5LdFrvU7dX/fR51824UyBI+MvO/F95lGSAo3N0jMi9sfBm8Ze9O188Bac0aeTzR/QRRGa6aGZFmz3TcKqYp+zhAMh1EqaAY6DqAFLAKlG5orH3GlgaOcEAyTLkqDC9MrqtTgHUtz4Bbi+z2+CCVS9w1cOG5FZRQAXSAOQpF/l8MHXE/wzrtSyIh18bLB38xvtvGepH/yToQD5xs+EzMXhoRL9raNe+3BRwKE78A9AoLFc9ZGHZvv+o0qDXkMyuglDryzQna9SFiGRb4R6UDdMEjAunrZx1xeMhtnwQFAicZ4P0dzo9t8PqDLd6TesUCGX81AOkUqllYi3P50FbGaLf6EggZ8QZH4d5zBtoJ8IbhpTSTdjq0h1uOoFa/KcSSg/KxBYozBezxQl42Q9cOwYv7T3FYMT8=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:

script:
  - cd /repo
  - sudo /bin/bash build.sh $DOCKER_USER $DOCKER_PASS $TRAVIS_BRANCH


