sudo: required 
language: cpp
services:
  - docker
env:
  global:
    - secure: "qyxW+KxLIaBXMvw841yO7bR2cAOSdYwfIe9Cr39fJ60UYl9B7YdAckXng6U8Xo69Pdt6wbuTRNEOOO7LqENo2YaGMA29y8tBW5pLau5Xm8TIGQs3bUtstbxggj8tbv35SZrMMlf4foIk6899UFLMMxaLmtl9ZDRF9tGZTe5Dt9BtrXYAM9Sfcycmtb4d+KugHkaRAP/5OIu7WdBReYsGv2y/Yw774gFbWrwztHh+dEfNGvy7wSVdy1LjigozrHXM6LpGmWW0WWfgvb6SZ9HiPhNSKFhaCFYkx3vYxN1mlKMZg7TwzzjEHRWIZAbfF6tMLnXDSXEfCXm/D8ZkHh7oTpEtr3Pfr4uUGRYdBiDCQv4X6StgS2gPtKEb2eHuj3fXjkZFjWbXvCsRN4P6GyPqZGHtJWlp7VKsNWugliQs9q7OjafDez8ReDxeA0Y5bI3yHNea5BqqUuwW2MOdv2zX7uVtU5UKcukhx8ejur7CWhHvE0osn1y7ur8xkTHqNhUzh1bxpaF4JfERssnMWet8FGxRuyewSvmmxooB6P9NgMWfUbbwixtw2P2IHT6O++PWJ4IfeUL/Xp3mznJFBt/CPnQ5RpRfJeehKNRwmRfDfNw9Vemek9Q5IQtXbpYEK3s3jjrlTxGOqsVHCKAwp53XAHf9VAwDoiMW41A2RX5vveI=" # DOCKER_USER
    - secure: "a20EL2YDLI7CcKyPglIZQzHE29AEvSeyyHApKIWScInXh+0gDzcWgSvYbv76uJeqYSlqQPkfeQW3ky7jIPL6ZfcKU4kYnrhHdoe8JxqqIkGJ1SzDSVdJQqFUIynfODOezXV0kyxstBs6smaw8ycmXMmzBw4L9VyJV775tTgQgZdWwmcaFyhsKJjHJVpVuuc+uOuH10iJuw1MywoqC13OUnV5qzPEa5wIkwHWuu9pZJIP/s1R2rjOjQUAw0D8Vrf4adpeZ22DoeGyi1wgt701NmtUexe29RDbemwTsOzeMY8exCQhCUPLEq7wsi82HECdEryVmZ1Z+bcVEkjv3SWkSWhiDUV2ewQw60mLzj2X6PEdng+o3mnJcKgy+rYlRnKXgCVfbldGwLXbBe9t3FdklXoASbZotIN8z2zjWTRPlaQhpozvI408bweC/d9q/k8oKrDxmFsgw+5yMcemlIILmOrI+qg/qXPF/FcxMdDCMmIgmSNGmxMuDeTMmdlWnnbUR95pT0MSfteVPL11CgzpVs0JIigzO1MyEoXhbBrE543foF7/hUnT2VPCo40gTMxoLkN8n5lG8E07sT8unQ4Xo9+qyOjC7ZxesX7GdQ10hZLse6b8Ml2RzsblBV3Xp3qn48pjGjC62ksho5p6ETVp+sbNCxcnBh5IkN4CHlU4YZQ=" # DOCKER_PASS
  - COMMIT=${TRAVIS_COMMIT::8}

script:
  - sudo /bin/bash build.sh $DOCKER_USER $DOCKER_PASS $TRAVIS_BRANCH


