sudo: required 
language: cpp
services:
  - docker
env:
  global:
    - secure: "AzEZqKDm8gAZiqCF5fgVYwUihW0wRIw3gv2neWJj5pxZ7jKib7HuspxBlEJqJ92cc7g4AzjR43ZFqHXJQnNBbJn0Gh+fzPnfbwuqttK4kex80oB/JtOTxSTO3wUoncDqjAKET4j+tWxoa8PAQcviZ6iigpYyYiXb5VGfw/OisKHNiPr1+KhHQJQjqHGHqblo8TMFsiz6rqVqAfungpveKUrKClK+Dywf168TDTb6udjs283PtT189opfCsX6EAlEW8MFbpc53jPAvcck5GB/anbYHW4l2/n5ytvpYoy18mIywtq/OUisoBpbd6HEZ8I4d5m1WRN5flOsc+6hkHGWVCOvbTXsP41f0ulv6m2KNF6Jh8ahfUi8bEdL058k19SuDK2xfxeuFCTdAziRqn1NLqNHMViiJ5hphmGswQLNlKTzVfzOAnI1TqwUJGBdvixLCfP/+On/6Vy7L7qSOo4kaBzXnhz+VHDccs2K1saohZ1wliH5zfLgmDfYAsMRP9nMnT4CRtgG4cWw+wbVsTjEtBZ710WYomv65SkAYsg0ugxGXaOz8xDgTcJrWfRs3VnYLmAQ75YxgFt42n2zrPLN1YNfxpGvUJ28Y92ko/7gzwxwCu+yfs+6EeIF72S1cDWSBZ+gj2Cc84bSsPcZK4YEC5FQxUJhWYgnaKCYswsQTlo=" # DOCKER_USER
    - secure: "NdfEwL3sUBMENZuizDk6A9KCfoEeLz2U8OYUk9JYfdX7aOMOwWJ9CWsUXN82SLVUeW6bAgAlMj0RnqlKR8O3izhdXfXkBNLPQkmQkZalNYQCPZaFzZx5/OXS6Eecz4bNxONV5SvQsYwXXceL4oIyV6NlICNtddYhMQ4TzIpHiG8ihdAfbpsB3lokzP/jlVPnMGEXqKxCyDvc91Y5mToL7ZmwOnSCNht64D2nmzQ5BeiORgI25wM8t13CLk5TC6EmmpWtn40/Q/puRgxtBB0kLih9Rs8co45txnVXwM7anr91JSE7AdbsRLN3EdMDNLUndekmXmFcgbb8AT/doXsBO24CMQig2yO6okHNA5u2amhrpWSH2sLmJKfnKzO3NSBkiujsgI2UPCs9jXcDZ5rEhQkfqIdnZmhixamki+sk0QVoy26LpLt42AMA7JG1fsOSTlaMgHHqSJYuiTB4v6tYb4GDNczltKAP0lpQlORMLiuPKloqDtqC6yO3DQkh7DrOUfeFkr60Ati2aeSW0kAweLdI4orNOOthKXSd8FjzQabxoLS89U4Jvdd8VHRcI9ew2KPHInK2YMJzzfyziwjb3/ywyEN0td02+JuYdyfITtzSFYn0EnKhgBP4wJE34ZgoVKcpx8otgPQ1SeVMExCRwNS7L1Nspc0hK7Tt1k2V+MU=" # DOCKER_PASS
    - COMMIT=${TRAVIS_COMMIT::8}
before_install:
  - sudo git clone https://github.com/spielhuus/docker-freedb-server.git /repo

script:
  - cd /repo
  - sudo /bin/bash build.sh
#  - sudo docker login -u $DOCKER_USER -p $DOCKER_PASS
#  - export REPO=spielhuus/x2go
#  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
#  - sudo docker build -f Dockerfile -t $REPO:$TAG .
#  - sudo docker push $REPO
